apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  # 1 replica, base stateful
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
    # recrée proprement la db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
              # mdp en secret
            - name: POSTGRES_USER
              value: appuser
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - appuser
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - appuser
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
            # prêt = ok pour connexions
          name: database
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
            - mountPath: /docker-entrypoint-initdb.d
              name: database-cm1
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - configMap:
            name: database-cm1
          name: database-cm1
